
#ifdef VENDOR_EDIT
obj-$(CONFIG_SYNAPTIC_OPPO13095) += synaptics_s3203/
#add for hall sensor
obj-$(CONFIG_HALL) += hall/
#add for pswtich sensor
obj-$(CONFIG_PSWITCH) += hall/
#add for dhall sensor
obj-$(CONFIG_DHALL_M1120) += hall/
#add for uei 
obj-$(CONFIG_UEI) += uei/
#endif
