#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_SYNAPTIC_OPPO13095) += synaptics_s3203_13095.o
obj-$(CONFIG_SYNAPTIC_OPPO13095) += synaptics_redremote.o
#endif