#
# Makefile for nfc devices
#
# wenjie.Liu@Prd.SysApp.PowerManager, 2014/03/18, Add for :NFC PN65T
# Rewritten to use pn544 driver.
obj-$(CONFIG_PN65T_NFC)		+= pn544_op.o
obj-$(CONFIG_PN65T_NFC)		+= p61.o
#obj-$(CONFIG_PN544_NFC)		+= pn544.o
#obj-$(CONFIG_NFC_PN533)		+= pn533.o
#obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o
#obj-$(CONFIG_NFC_QNCI)		+= nfc-nci.o

#ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
